name: Sustainable Materials Research Group
url: http://kunalvrm555.tech

exclude: [bibble, README.md, Makefile, screenshot.png]

# colorize code snippets with the pygments module
highlighter: pygments

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html

# Sections on the "people" page.
roles:
  - key: faculty
    name: Faculty
  - key: staff
    name: Staff
  - key: postdoc
    name: Researchers
  - key: ugrad
    name: Undergraduate Students
  - key: ugrad-past
    name: Past Undergraduate Students
  - key: collaborator
    name: Collaborators
  - key: alum
    name: Alumni

# Number of news stories on the front page.
front_page_news: 8

# Base pathname for links.
base: ''

# make pages for the _projects folder
collections:
  projects:
    output: true

# Navigation bar links.
navigation:
  - title: Home
    link: /
  - title: People
    link: /#people
  - title: Research
    link: /research.html
  - title: Publications
    link: /publications.html
  - title: Connect
    link: /connect.html
